// <auto-generated />
namespace ProjetoCliente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201809141432044_add_inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
