// <auto-generated />
namespace ProjetoCliente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ater_tipos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ater_tipos));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181401495_ater_tipos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
